modLoader="javafml"
loaderVersion="[${forge_min_version},)"
issueTrackerURL="${mod_issues}"
license="${license_name}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
credits="${mod_credits}"
authors="${mod_authors}"
description="${mod_description}"

[[dependencies.${mod_id}]]
modId="genlib"
mandatory=true
versionRange="[${genlib_version},)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="create"
mandatory=false
versionRange="[0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="[${forge_min_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="[${mc_version},)"
ordering="NONE"
side="BOTH"
