org.gradle.configureondemand=false
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=512m
org.gradle.daemon=false

group=io.github.joseetoon

mod_version=7.8-1.21.1
mod_core_version=7.8
mod_name=Ore Stone Variants
mod_id=osv
mod_short=OSV
mod_vendor=joseetoon
mod_authors=joseetoon
mod_credits=MCP, pupnewfster
mod_issues=https://github.com/joseetoon/OreStoneVariants/issues
mod_description=A powerful utility for generating new blocks when given a foreground and background.
license_name=GPLv3

archive_base=OSV
platform=Partial

mc_version=1.21.1
enabled_platforms=neoforge
architectury_version=13.0.8
architectury_loom_version=1.6.422
neoforge_version=21.1.209
neo_version_range=[21.1.209,)
loader_version_range=[1,)
loader_version=0.16.10
genlib_version=1.2.22
create_maven_neoforge_version=6247669
fresult_version=2.0-BETA-5
fastnoise_version=0.8
hjson_version=3.0.0-C11
