pluginManagement {
    repositories {
        maven { name = 'Fabric'; url = 'https://maven.fabricmc.net/' }
        maven { name = 'Forge'; url = 'https://maven.minecraftforge.net/' }
        maven { name = 'NeoForged'; url = 'https://maven.neoforged.net/releases' }
        maven { name = 'Architectury'; url = 'https://maven.architectury.dev' }
        gradlePluginPortal()
        mavenCentral()
    }
    plugins {
        id "architectury-plugin" version "3.4-SNAPSHOT"
        id "dev.architectury.loom" version "1.11-SNAPSHOT"
    }
}

rootProject.name = 'OSV'

include 'common', 'neoforge'
