architectury {
    common("forge")
}

loom {
    mixin {
        defaultRefmapName = "osv.refmap.json"
    }
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:$loader_version"
    modApi "dev.architectury:architectury:$architectury_version"
    modCompileOnly "io.github.joseetoon:genlib-forge:$genlib_version"
}
