architectury {
    common("neoforge")
}

loom {
    mixin {
        defaultRefmapName = "osv.refmap.json"
    }
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:$loader_version"
    modApi "dev.architectury:architectury:$architectury_version"
    bundle group: "com.github.PersonTheCat", name: "FResult", version: fresult_version
    bundle group: "com.github.PersonTheCat", name: "FastNoise", version: fastnoise_version
    bundle group: "com.github.PersonTheCat", name: "hjson-java", version: hjson_version
}
